#!/usr/bin/env python3
"""build_plan.py — render growth-plan.json to a self-contained HTML deliverable.

This is the ONLY presentation component and the artifact the founder actually
opens. It performs NO scoring and invents NO numbers: the `metrics` block is
read as authoritative precomputed script output (envelopes included) and
rendered verbatim with its provenance. The model assembles growth-plan.json
(positioning, calendar, scripts) around those script outputs, then runs this.

Compliance defense-in-depth: any calendar post marked promotional that lacks a
disclosure block gets the standard block stamped in by this renderer — the
deliverable can never contain an undisclosed promo post.

The rendered page also carries the community-dataset contribution banner
(config-gated via ui.contribution_reminder) — the nudge lives in the
deliverable the user opens, not in stderr.

CLI:
    build_plan.py growth-plan.json [--out growth-plan.html]
"""
from __future__ import annotations

import argparse
import html
import json
import os
import sys
from typing import Any, Optional

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "federation"))

from compliance import REPURPOSE_RULE, disclosure_block  # noqa: E402
from notifications import contribution_banner_html  # noqa: E402

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__ — GrowthKit plan</title>
<style>
  :root { --bg:#0b0f14; --card:#141b24; --ink:#e6edf3; --mut:#8b98a5; --line:#222d3a;
          --edu:#1f6feb; --ent:#8957e5; --promo:#d29922; }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--ink);
         font:15px/1.55 system-ui,-apple-system,Segoe UI,Roboto,sans-serif; }
  header { padding:28px 24px; border-bottom:1px solid var(--line); }
  h1 { margin:0 0 6px; font-size:22px; }
  h2 { font-size:18px; margin:26px 0 10px; }
  .prov { color:var(--mut); font-size:13px; }
  .wrap { max-width:1000px; margin:0 auto; padding:24px; }
  .card { background:var(--card); border:1px solid var(--line); border-radius:12px;
          padding:18px 20px; margin:0 0 18px; }
  .pill { display:inline-block; padding:2px 10px; border-radius:999px; font-size:12px;
          border:1px solid var(--line); margin:0 6px 4px 0; color:var(--mut); }
  .pill.edu { border-color:var(--edu); color:#79b8ff; }
  .pill.ent { border-color:var(--ent); color:#c8a5ff; }
  .pill.promo { border-color:var(--promo); color:#e8c66b; }
  .bar { display:flex; height:12px; border-radius:999px; overflow:hidden; margin:10px 0 4px; }
  .bar div:nth-child(1){ background:var(--edu);} .bar div:nth-child(2){ background:var(--ent);}
  .bar div:nth-child(3){ background:var(--promo);}
  .post { border:1px solid var(--line); border-radius:10px; padding:14px 16px; margin:10px 0; }
  .post h4 { margin:0 0 6px; font-size:15px; }
  .k { color:var(--mut); font-size:12px; text-transform:uppercase; letter-spacing:.6px; }
  .v { margin:2px 0 10px; white-space:pre-wrap; }
  .disc { border-left:4px solid var(--promo); background:#1c160a; color:#e8c66b;
          border-radius:8px; padding:10px 12px; font-size:13px; margin:8px 0; }
  table { width:100%; border-collapse:collapse; font-size:14px; }
  th, td { text-align:left; padding:8px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { color:var(--mut); font-size:12px; text-transform:uppercase; letter-spacing:.6px; }
  .conf-HIGH { color:#56d364; } .conf-MEDIUM { color:#e8c66b; }
  .conf-LOW { color:#f0883e; } .conf-NONE { color:#f85149; }
  .flag { color:#f0883e; font-size:12px; }
  button { cursor:pointer; background:#1f6feb; color:#fff; border:0; border-radius:8px;
           padding:6px 11px; font-size:12px; margin:2px 6px 0 0; }
  footer { color:var(--mut); font-size:12px; padding:18px 24px; border-top:1px solid var(--line); }
  ul { margin:6px 0; padding-left:18px; }
</style>
</head>
<body>
<header>
  <h1>__TITLE__ — short-form growth plan</h1>
  <div class="prov">__VARIANT__</div>
  <div class="prov">Every number below carries its source and confidence. Nothing is guessed:
  metrics come from GrowthKit's deterministic scripts on your own data.</div>
</header>
<div class="wrap">
__CONTRIB__
__BODY__
</div>
<footer>Generated by GrowthKit (github.com/Ahad690/growthkit-skill) · code MIT, data CC-BY-4.0.
Heuristics are labeled; attribution is banded; compliance blocks are mandatory on promotional posts.</footer>
<script>
document.addEventListener('click', function (e) {
  if (e.target.tagName !== 'BUTTON' || !e.target.dataset.copy) return;
  const el = document.getElementById(e.target.dataset.copy);
  if (!el) return;
  navigator.clipboard.writeText(el.textContent).then(() => {
    const t = e.target.textContent; e.target.textContent = 'Copied!';
    setTimeout(() => { e.target.textContent = t; }, 1200);
  });
});
</script>
</body>
</html>
"""


def esc(x: Any) -> str:
    return html.escape(str(x)) if x is not None else ""


def _fmt_value(m: dict[str, Any]) -> str:
    unit = m.get("unit") or ""
    if m.get("value") is None:
        return "no data"
    v = f"{unit}{m['value']}" if unit == "$" else f"{m['value']}{unit}"
    if m.get("low") is not None and m.get("high") is not None and m["low"] != m["high"]:
        lo = f"{unit}{m['low']}" if unit == "$" else f"{m['low']}{unit}"
        hi = f"{unit}{m['high']}" if unit == "$" else f"{m['high']}{unit}"
        return f"{v} (band {lo}–{hi})"
    return v


def render_positioning(plan: dict[str, Any]) -> str:
    pos = plan.get("positioning") or {}
    if not pos:
        return ""
    parts = [f'<div class="card"><h2 style="margin-top:0">Positioning</h2>']
    if pos.get("statement"):
        parts.append(f'<p class="v" style="font-size:16px">{esc(pos["statement"])}</p>')
    if pos.get("jtbd"):
        parts.append(f'<div class="k">Job to be done</div><p class="v">{esc(pos["jtbd"])}</p>')
    dun = pos.get("dunford") or {}
    if dun:
        parts.append("<ul>")
        for key in ("alternatives", "unique_attributes", "value", "icp", "category"):
            if dun.get(key):
                parts.append(f"<li><b>{esc(key.replace('_', ' ').title())}:</b> {esc(dun[key])}</li>")
        parts.append("</ul>")
    parts.append("</div>")
    return "".join(parts)


def render_pillars(plan: dict[str, Any]) -> str:
    pil = plan.get("pillars") or {}
    if not pil:
        return ""
    edu = float(pil.get("educational", 0)); ent = float(pil.get("entertainment", 0))
    pro = float(pil.get("promotional", 0))
    return (
        '<div class="card"><h2 style="margin-top:0">Content pillars</h2>'
        f'<div class="bar"><div style="width:{edu*100:.0f}%"></div>'
        f'<div style="width:{ent*100:.0f}%"></div><div style="width:{pro*100:.0f}%"></div></div>'
        f'<span class="pill edu">Educational {edu*100:.0f}%</span>'
        f'<span class="pill ent">Entertainment {ent*100:.0f}%</span>'
        f'<span class="pill promo">Promotional {pro*100:.0f}%</span>'
        "</div>"
    )


def render_calendar(plan: dict[str, Any]) -> str:
    weeks = plan.get("calendar") or []
    if not weeks:
        return ""
    out = ['<h2>Content calendar</h2>']
    pid = 0
    for wk in weeks:
        out.append(f'<div class="card"><h3 style="margin:0 0 8px">Week {esc(wk.get("week", "?"))}</h3>')
        for post in wk.get("posts", []):
            pid += 1
            pillar = str(post.get("pillar", "")).lower()
            cls = {"educational": "edu", "entertainment": "ent", "promotional": "promo"}.get(pillar, "")
            promo = bool(post.get("promotional")) or pillar == "promotional"
            out.append('<div class="post">')
            out.append(f'<h4>{esc(post.get("day", ""))} <span class="pill {cls}">{esc(post.get("pillar", ""))}</span></h4>')
            body_id = f"post{pid}"
            out.append(f'<div id="{body_id}">')
            for key, label in (("hook", "Hook (0–3s)"), ("value", "Value"), ("cta", "CTA"),
                               ("on_screen_text", "On-screen text"), ("spoken_keywords", "Spoken keywords")):
                if post.get(key):
                    out.append(f'<div class="k">{label}</div><div class="v">{esc(post[key])}</div>')
            tags = post.get("hashtags") or []
            if tags:
                out.append(f'<div class="k">Hashtags</div><div class="v">{esc(" ".join(tags))}</div>')
            out.append("</div>")
            if post.get("sound_guidance"):
                out.append(f'<div class="k">Sound</div><div class="v">{esc(post["sound_guidance"])}</div>')
            if promo:
                # Hard gate in depth: a promo post NEVER renders without the block.
                disc = post.get("disclosure") or disclosure_block()
                out.append(f'<div class="disc"><b>Mandatory disclosure:</b> {esc(disc)}</div>')
            out.append(f'<button data-copy="{body_id}">Copy script</button>')
            out.append("</div>")
        out.append("</div>")
    return "".join(out)


def render_metrics(plan: dict[str, Any]) -> str:
    metrics = plan.get("metrics") or []
    if not metrics:
        return ""
    rows = []
    for m in metrics:
        conf = esc(m.get("confidence", ""))
        flags = ", ".join(m.get("flags") or [])
        rows.append(
            "<tr>"
            f"<td>{esc(m.get('label', ''))}</td>"
            f"<td>{esc(_fmt_value(m))}</td>"
            f'<td class="conf-{conf}">{conf}</td>'
            f"<td>{esc(m.get('method', ''))}</td>"
            f"<td>{esc(', '.join(m.get('sources') or []))}</td>"
            f'<td class="flag">{esc(flags)}</td>'
            "</tr>"
        )
    return (
        '<div class="card"><h2 style="margin-top:0">Metrics — with provenance</h2>'
        "<table><tr><th>Metric</th><th>Value</th><th>Confidence</th><th>Method</th>"
        "<th>Sources</th><th>Flags</th></tr>" + "".join(rows) + "</table></div>"
    )


def render_compliance(plan: dict[str, Any]) -> str:
    comp = plan.get("compliance") or {}
    out = ['<div class="card"><h2 style="margin-top:0">Compliance checklist</h2><ul>']
    if comp.get("account_type"):
        out.append(f"<li><b>Account type:</b> {esc(comp['account_type'])}"
                   + (" — Commercial Music Library or original/owned audio ONLY"
                      if comp["account_type"] == "business" else "") + "</li>")
    if comp.get("category"):
        flag = comp.get("category_flag")
        out.append(f"<li><b>Category:</b> {esc(comp['category'])}"
                   + (f' — <span class="flag">{esc(flag)}</span>' if flag else " — no restriction flag") + "</li>")
    for note in comp.get("notes") or []:
        out.append(f"<li>{esc(note)}</li>")
    out.append(f"<li><b>Repurposing:</b> {esc(REPURPOSE_RULE)}</li>")
    out.append("</ul></div>")
    return "".join(out)


def render(plan: dict[str, Any]) -> str:
    product = plan.get("product") or {}
    title = product.get("name") or "Your product"
    variant_bits = [b for b in (product.get("variant"), product.get("why_variant")) if b]
    body = (
        render_positioning(plan)
        + render_pillars(plan)
        + render_calendar(plan)
        + render_metrics(plan)
        + render_compliance(plan)
    )
    page = HTML_TEMPLATE.replace("__TITLE__", esc(title))
    page = page.replace("__VARIANT__", esc(" — ".join(variant_bits)))
    page = page.replace("__CONTRIB__", contribution_banner_html())
    page = page.replace("__BODY__", body)
    return page


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Render growth-plan.json to a self-contained HTML deliverable.")
    p.add_argument("plan", help="Path to growth-plan.json (assembled by the skill)")
    p.add_argument("--out", default="growth-plan.html", help="Output HTML path")
    args = p.parse_args(argv)

    with open(args.plan, encoding="utf-8") as fh:
        plan = json.load(fh)
    page = render(plan)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(page)
    print(json.dumps({"written": args.out,
                      "posts": sum(len(w.get("posts", [])) for w in plan.get("calendar", [])),
                      "metrics": len(plan.get("metrics", []))}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
